INSERT INTO TBL_CONTACT (NAME, AGE, GENDER, TELEPHONE, FAVORITE) VALUES ('Rodrigo Kako', 23, 1, '3232233', true)
INSERT INTO TBL_CONTACT (NAME, AGE, GENDER, TELEPHONE, FAVORITE) VALUES ('Aline', 23, 1, '32332443', true)
INSERT INTO TBL_CONTACT (NAME, AGE, GENDER, TELEPHONE, FAVORITE) VALUES ('Seu jorge', 45, 3, '999999999', false)